### ISSUE TITLE
Issue with longer text.

### ISSUE THREAD

**Issue by IAmEska** [comahe-de/i18n4k#1]
Hello,
first at all thanks for this library it really helped me to solve multilanguage feature in my kotlin/js react web application. 
I found out there is an issue with the longer text. If you have longer text in properties file it won't generate the translation .kt file correctly that results into build error.

property file:
`longTextExample=Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus faucibus molestie nisl. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Pellentesque ipsum. Integer malesuada. Fusce wisi. Nullam dapibus fermentum ipsum. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Quisque tincidunt scelerisque libero. Etiam posuere lacus quis dolor. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Pellentesque sapien.`

iIt will generate string in translation .kt file:
"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus faucibus molestie nisl.
          Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis
          velit mauris vel metus. Pellentesque ipsum. Integer malesuada. Fusce wisi. Nullam dapibus
          fermentum ipsum. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
          ut aliquip ex ea commodo consequat. Integer rutrum, orci vestibulum ullamcorper ultricies,
          lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Quisque tincidunt
          scelerisque libero. Etiam posuere lacus quis dolor. In laoreet, magna id viverra
          tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Neque porro
          quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia
          non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat
          voluptatem. Pellentesque sapien.",

expected result:
"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus faucibus molestie nisl."
          + "Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis"
          + "velit mauris vel metus. Pellentesque ipsum. Integer malesuada. Fusce wisi. Nullam dapibus"
          + "fermentum ipsum. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi"
          + "ut aliquip ex ea commodo consequat. Integer rutrum, orci vestibulum ullamcorper ultricies,"
          + "lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Quisque tincidunt"
          + "scelerisque libero. Etiam posuere lacus quis dolor. In laoreet, magna id viverra"
          + "tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Neque porro"
          + "quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia"
          + "non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat"
          + "voluptatem. Pellentesque sapien.",

**Comment by comahe-de** [comment]
@IAmEska Thanks for the hint. The used library "KotlinPoet" did some unexpected formatting. Will be fixed in v0.1.1 (pipeline currently running)
