### ISSUE TITLE
Question: locale changing for jvm source set

### ISSUE THREAD

**Issue by finke-ba** [comahe-de/i18n4k#11]
Hello @comahe-de !
I'm looking for i18n library for Kotlin Multiplatform and I have jvm and js source set only(Ktor and React).
My question is about locale changing - it's totally clear that changing locale atomic ref in I18n4kConfig is ok for the frontend(js or mobile app) as you have separate application instance per client, but what about backend? You have only one backend instance for many clients and each client can have different locale.
For example we have 2 clients with different locale(client_1 - en, client_2 - de). Each client makes many parallel http requests with different locale. Each request contains many steps for generation some localized text documents, and the response time can be, for example, from 500ms to 20sec.
That's means that for each request I will change locale atomic ref in I18n4kConfig and it could happen that client_1 request is not finished yet, but client_2 request is already begun. What would happen in this case? Would client_1 receive part of the response in en and part in de?

**Comment by comahe-de** [comment]
Hi, 
you could set the required locale when getting the String:

e.g. you could replace this:

        label1.text = MyMessages.title()
        label2.text = MyMessages.sayHello(textField.text)

with that: 

        val myLocale : Locale = ...
        label1.text = MyMessages.title.toString(myLocale)
        label2.text = MyMessages.sayHello[textField.text].toString(myLocale)

**Comment by finke-ba** [comment]
Thank you for this advise, this could help me.
What do you think, is it possible to have jvm specific implementetion of MessageBundle with Locale stored in scope of request(something like https://kotlinlang.org/docs/coroutine-context-and-dispatchers.html#thread-local-data)?

**Comment by comahe-de** [comment]
Normally you store the locale in the session or request and then pass it down the function you call.

If you don't want to do this, you could write your own implementation of `I18n4kConfig` where you store the request locale in a thread local member variable. Then you create a global instance (Kotlin object) of this new class and assign the reference also to the global `i18n4k` variable. Then, at the beginning of the request processing, you store the locale in your global instance. But this will only work, if the entire processing is done in this single thread.

**Comment by comahe-de** [comment]
Another alternative is to use `LocalizedString` instead of `Sting` in the results of your processing. And only at the end, when you build the response for the request, you call the `toString` method with the locale of the request.

**Comment by finke-ba** [comment]
Thank you very much, it's clear for me, we can close this issue!
