### ISSUE TITLE
Support for Apple silicon

### ISSUE THREAD

**Issue by aftabahmadTW** [comahe-de/i18n4k#14]
Would be nice to add support for the Apple silicon target introduced here: https://kotlinlang.org/docs/multiplatform-share-on-platforms.html#target-shortcuts-and-arm64-apple-silicon-simulators

From the dependencies [here](https://github.com/comahe-de/i18n4k/blob/master/i18n4k-core/build.gradle.kts#L37), I checked that `atomicfu` and `kotlinx-collections-immutable` both support `iosSimulatorArm64`.

Might be worth revisiting that list and seeing if those dependencies now support those additional targets.

Happy to submit a PR.

**Comment by comahe-de** [comment]
Fixed by  PR #15. Thank you!
