### ISSUE TITLE
Add common "ios" sources sets

### ISSUE THREAD

**Issue by comahe-de** [comahe-de/i18n4k#18]
@aftabahmadTW [wrote](https://github.com/comahe-de/i18n4k/pull/15#issuecomment-1114292911)

> I think it could be worth splitting the native srcset into a few a smaller ones. I think it's worth having a seperate one for iOS.
> 
> That would allow us to fix this issue for iOS native at least:
> https://github.com/comahe-de/i18n4k/blob/f337f99b62b39096abab42232978b76a55b48dfb/i18n4k-core/src/nativeMain/kotlin/de/comahe/i18n4k/Locale.kt#L25
>
> Since we can use the foundation library and access NSLocale.

**Comment by comahe-de** [comment]
Sure we may add something like this to the `build.gradle.kts`

        val iosMain = create("iosMain")
        val iosTest = create("iosTest")
        
        iosMain.dependsOn(nativeCommonMain)
        iosTest.dependsOn(nativeCommonTest)

        val iosArm32Main by getting {
            dependsOn(iosMain)
        }
        val iosArm32Test by getting {
            dependsOn(iosTest)
        }

        val iosArm64Main by getting {
            dependsOn(iosMain)
        }
        val iosArm64Test by getting {
            dependsOn(iosTest)
        }

        val iosX64Main by getting {
            dependsOn(iosMain)
        }
        val iosX64Test by getting {
            dependsOn(iosTest)
        }

        val iosSimulatorArm64Main by getting {
            dependsOn(iosMain)
        }
        val iosSimulatorArm64Test by getting {
            dependsOn(iosTest)
        }
 
Maybe also a common source set for Mac & iOS?

Could you make than a PR with the iOS specific code, as I don't have a Mac to test it.

**Comment by aftabahmadTW** [comment]
> Maybe also a common source set for Mac & iOS?
> 
> @aftabahmadTW Could you make than a PR with the iOS specific code (as a new issue), as I don't have a Mac to test it.

Nice, yeah Mac & iOS and can be combined. I'll create a PR

**Comment by comahe-de** [comment]
Fixed by 1a46d58614eb11d8f5563f7615f5e132534ae526
