### ISSUE TITLE
Issues in latest release 0.4.0

### ISSUE THREAD

**Issue by aftabahmadTW** [comahe-de/i18n4k#20]
The new targets were added here: https://github.com/comahe-de/i18n4k/commit/89ace5d2e3021051031f597f469aa6e111901e79 but don't seem to be published in the new version:  https://search.maven.org/search?q=de.comahe.i18n4k

I also seem to get an error when trying to build the new version:

```
An exception occurred applying plugin request [id: 'de.comahe.i18n4k', version: '0.4.0']
> Failed to apply plugin 'de.comahe.i18n4k'.
   > Could not create an instance of type de.comahe.i18n4k.gradle.plugin.I18n4kExtension.
      > Could not generate a decorated class for type I18n4kExtension.
         > de/comahe/i18n4k/messages/formatter/MessageFormatter
```

**Comment by comahe-de** [comment]
> The new targets were added here: https://github.com/comahe-de/i18n4k/commit/89ace5d2e3021051031f597f469aa6e111901e79 but don't seem to be published in the new version: https://search.maven.org/search?q=de.comahe.i18n4k

The new targets where missing in  `BuildTools#getMultiPlatformPublicationsToAllow`, also some other Apple target where placed wrong.

**Comment by comahe-de** [comment]
> I also seem to get an error when trying to build the new version:
> 
> ```
> An exception occurred applying plugin request [id: 'de.comahe.i18n4k', version: '0.4.0']
> > Failed to apply plugin 'de.comahe.i18n4k'.
>    > Could not create an instance of type de.comahe.i18n4k.gradle.plugin.I18n4kExtension.
>       > Could not generate a decorated class for type I18n4kExtension.
>          > de/comahe/i18n4k/messages/formatter/MessageFormatter
> ```

I cannot reproduce this. Do you also have this error when you run one of the example projects of this repository?

**Comment by aftabahmadTW** [comment]
> I cannot reproduce this. Do you also have this error when you run one of the example projects of this repository?

Strange, I tried it first on my own project but I seem to also get it on the example ones too. I ran the `example-mpp` project.

**Comment by comahe-de** [comment]
Ok, the missing Apple libs are now in the Maven repository.

And now I can reproduce the plugin problem when I delete the artifacts from my local Maven repository (which was fill by 'publishToMavenLocal' task). Now, I have to figure out what is wrong with the public repositories.

**Comment by comahe-de** [comment]
@aftabahmadTW I redeployed the plugin and still the error. Then I deleted the Gradle cache (HOME/.gradle/caches) and then it worked. Could you also try this?

**Comment by aftabahmadTW** [comment]
I'll try it again
