### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by minhpham-tyme** [comahe-de/i18n4k#25]
The generated code does not support Unicode as the images below. Could I miss something?

<img width="940" alt="Screen Shot 2022-09-30 at 10 23 25" src="https://user-images.githubusercontent.com/76985216/193183373-c73f5c67-eb6b-421c-be43-94c3777ee62c.png">
<img width="974" alt="Screen Shot 2022-09-30 at 10 23 51" src="https://user-images.githubusercontent.com/76985216/193183415-8f2e21ff-f3e8-4cb8-a526-99a914e22b15.png">

**Comment by comahe-de** [comment]
This should not be a problem see: 
* https://github.com/comahe-de/i18n4k/blob/master/i18n4k-generator/src/test/files/source_text/Abba_en.properties#L15
* https://github.com/comahe-de/i18n4k/blob/master/i18n4k-generator/src/test/files/generated_code/JVM/Abba.kt#L137

Have you set everywhere UTF-8 encoding?

**Comment by minhpham-tyme** [comment]
Thank @comahe-de for quick response, I use IntelliJ IDE with UTF-8, could I miss any configuration??? 😹 
Could you please help me check this with content
`cây lồ ô trong bụi trễ nguyễn nhưng không thực tế a truyện `

<img width="245" alt="Screen Shot 2022-09-30 at 16 43 02" src="https://user-images.githubusercontent.com/76985216/193243736-8fa34273-410b-4933-bee6-76a4af59c73e.png">

**Comment by comahe-de** [comment]
Check the content of the properties file in another editor. With the default setting of InteliJ you will get this:

![image](https://user-images.githubusercontent.com/78822384/193254545-226a326c-caac-407d-9a6e-3ac562be5b88.png)

For correct behaviour set this:

![image](https://user-images.githubusercontent.com/78822384/193254740-2081133c-950f-492b-bb8c-1736db47b475.png)

Which will result to this:

![image](https://user-images.githubusercontent.com/78822384/193254928-cb08de78-9ffe-4b35-8961-6a5e63b96a86.png)

Or set this:

![image](https://user-images.githubusercontent.com/78822384/193255174-cb8c4d70-f88b-46ff-ba12-d110270e1ad8.png)

Which will result to this:

![image](https://user-images.githubusercontent.com/78822384/193255237-52354ec1-632e-48d1-ab92-487379df8601.png)

**Comment by minhpham-tyme** [comment]
Wow it work, thank @comahe-de , you save my time for this issue and for localization on desktop Kotlin.

**Comment by MaxBQb** [comment]
It would be really helpful to mention such an important detail in the README :)

**Comment by comahe-de** [comment]
@MaxBQb Ok. See https://github.com/comahe-de/i18n4k?tab=readme-ov-file#hints-for-intelj-usage
