### ISSUE TITLE
Get a translation through an identifier

### ISSUE THREAD

**Issue by orelvis15** [comahe-de/i18n4k#26]
Hello, good afternoon.

I am using the lib to manage the translations of a desktop app but I need to get the translations through an identifier sent from the backend, is it possible?.

For example, the backend sends ID_SMS and has a method like `MYMESSAGE.fromKey("ID_SMS")` and returns me the translation.

**Comment by MarcelHeckel** [comment]
Hi @orelvis15 ,

This use case is currently not considered. Maybe I will extend the lib in future.

Currently you could use reflections:

In your build.gradel.kts, add this ` implementation(kotlin("reflect"))` to the dependencies.

In the code you can do this:

    // transfer name to the client... and maybe additional parameters for the string
    println(MyMessages::title.name) // prints "title"
    println(MyMessages::sayHello.name) // prints "sayHello"

    // on the client, look for the member with the given name
    var string0: LocalizedString =
        MyMessages::class.members.first { member -> member.name == "title" }
            .call(MyMessages) as LocalizedString;
    println(string0.toString())

    // In this example, one parameter is expected for the string,
    // that is why LocalizedStringFactory1 is used.
    var string1: LocalizedStringFactory1 =
        MyMessages::class.members.first { member -> member.name == "sayHello" }
            .call(MyMessages) as LocalizedStringFactory1;
    println(string1.get("World"))

**Comment by comahe-de** [comment]
@orelvis15 Now you may also have a look at the branch "messages_keys". Install the version "0.6.0-SNAPSHOT"  locally via the Gradle task "publishToMavenLocal"

In this version you can get the key via the `messageKey` property, e.g.  `MyMessages.sayHello.messageKey`, And the corresponding message object by `MyMessages.getEntryByKey("sayHello")`.

Some unit tests are still missing for this. But I think I can publish a new version during the next two weeks. I will also update to the new Kotlin version.

**Comment by orelvis15** [comment]
@comahe-de Perfect! I'm going to use it today! Thank you very much for this new feature, I'll let you know how it went as soon as I try it. greetings!.

**Comment by orelvis15** [comment]
@comahe-de I am testing the version "0.6.0-SNAPSHOT", it is just giving me an error in the generation of the code.

The integer literal does not conform to the expected type String

It seems that the `getLocalizedString0(0)` method now needs another `String` parameter 
`getLocalizedString0("key", 0)`

**Comment by comahe-de** [comment]
@orelvis15 Yes, I have forgot to say, that you need to add the local Maven repository to the plugin repository list in `settings.gradle.kts`, so that the local build plugin is used.  See here: https://github.com/comahe-de/i18n4k/blob/messages_keys/examples/example-mpp/settings.gradle.kts#L5. Don't forget also to use the "0.6.0-SNAPSHOT" version of the plugin.

Than call the Gradle task `clearI18n4kFiles` and than `generateI18n4kFiles`

**Comment by comahe-de** [comment]
v0.6.0 is out
