### ISSUE TITLE
Arabic shows up as ?????

### ISSUE THREAD

**Issue by yebaital** [comahe-de/i18n4k#29]
```
Column {
            Text(Strings.homeScreen(localization.locale))
            Box(Modifier.height(Dp(12.0f))){}
            Text("العربية")
        }
```
![2023-06-30_00-08](https://github.com/comahe-de/i18n4k/assets/10247142/8567e71e-bb81-4b4e-90ae-87f705c4d119)

**Comment by comahe-de** [comment]
Hi @yebaital,

Can you check your properties files that they are correctly encode as UTF-8. See also the discussion in issue #25.
