### ISSUE TITLE
Encoding problem on Linux (Ubuntu)

### ISSUE THREAD

**Issue by solvek** [comahe-de/i18n4k#3]
I have create properties file. It stored as UTF-8:
(Contains cyrilic content)

```
google_login=Зайти з Google
logout=Вийти
```

However the generated kt file has a strange content:

```Kotlin
private object Str_uk : MessagesProvider {
  private val _data: Array<String?> = arrayOf(
      "Ð\u0097Ð°Ð¹Ñ\u0082Ð¸ Ð· Google",
      "Ð\u0092Ð¸Ð¹Ñ\u0082Ð¸")

  public override val locale: Locale = Locale("uk")

  public override val size: Int = _data.size

  public override fun `get`(index: Int): String? = _data[index]
}
```

**Comment by comahe-de** [comment]
@solvek Will be fixed in the next release (in the next days). Until then you can use escape sequences (e.g. via this https://dencode.com/string/unicode-escape)

**Comment by comahe-de** [comment]
@solvek v0.1.2 released. Please try if it is working as expected now.

**Comment by solvek** [comment]
Now it works like a charm.
Thanks for such a great library and quick responses!
