### ISSUE TITLE
[Question] Available locales from i18n4kConfig

### ISSUE THREAD

**Issue by Griefed** [comahe-de/i18n4k#32]
Heyo comahe-de,

is it possible to get a list of available i18n locales from the config object?
Say we've got multiple language-bundles in a project: en_GB, de_DE so on and so forth
Would it be possible to somehow retrieve a list which reflects those bundle-locales?

Cheers,
Griefed

**Comment by comahe-de** [comment]
There is the `locales` field in the `MessageBundle`
 
https://github.com/comahe-de/i18n4k/blob/master/i18n4k-core/src/commonMain/kotlin/de/comahe/i18n4k/messages/MessageBundle.kt#L83C10-L83C10

**Comment by Griefed** [comment]
I saw that each bundle has the `locales` available, but was wondering whether the config would allow for a centralized way of acquiring available locales. I've got a multi-module project in which every module has its own message bundle.
So the best way to gather a meaningful list of available locales is to get all bundles locales and collect to one list.

Aight. Thank you!

Cheers,
Griefed
