### ISSUE TITLE
How to handle same language for different countries

### ISSUE THREAD

**Issue by danielpassos** [comahe-de/i18n4k#34]
Hi,

How do I handle the same languages for different countries? 

For example:

* `en_US` and `en_CA`
 * `pt_BR` and `pt_PT`
 * `es_ES` and `es_AR`

I tried to name the `properties` files with *language_COUNTRY* and pass the full locale `Locale("pt", "BR")` but that did not work.

**Comment by danielpassos** [comment]
I also noticed even if I have only the language in the file name and pass the full locale the translation it does not work. 

For example, I have the file `I18n_en.properties` and pass the locale like `Locale("en", "US")`

**Comment by comahe-de** [comment]
Hi @danielpassos!

Yes that is a missing feature. 

I have made a first implementation in branch https://github.com/comahe-de/i18n4k/tree/34-how-to-handle-same-language-for-different-countries

You may check it out and run "gradle publishToMavenLocal" to try it locally (by using version "0.7.0-SNAPSHOT")

**Comment by trentkan** [comment]
Currently just searching through the `locales` object to find whichever `language-region` matches what I pass in but this feature would be useful. 

One thing I noticed:
If I specify the source code locale as `en_US`, it gets generated correctly but within the `locales` object it's all lowercased.

build.gradle.kts
```
    i18n4k {
        sourceCodeLocales = listOf("en_US")
    }
```

generated code - notice the locale is correctly capitalized
```
/**
 * Translation of message bundle 'messages' for locale 'en_US'. Generated by i18n4k.
 */
private object messages_en_US : MessagesProvider {
  @JvmStatic
  private val _data: Array<String?> = arrayOf(
      "Hello, {0}!")

  override val locale: Locale = Locale("en_US")

  override val size: Int
    get() = _data.size

  override fun `get`(index: Int): String? = _data[index]
}
```

Within the locales object though, I see `en_us`. My other locale is es_ES and that is parsed correctly into the Locale object.

**Comment by comahe-de** [comment]
Hi @trentkan,

Yes that is also missing. I have updated the generator and examples in the branch  https://github.com/comahe-de/i18n4k/tree/34-how-to-handle-same-language-for-different-countries

So you may try it and give me feedback: 
* add `mavenLocal()` to your plugin repos (https://github.com/comahe-de/i18n4k/blob/master/examples/example-jvm/settings.gradle.kts#L6)
* run "gradle publishToMavenLocal"
*  use version "0.7.0-SNAPSHOT"

**Comment by danielpassos** [comment]
> Hi @danielpassos!
> 
> Yes that is a missing feature.
> 
> I have made a first implementation in branch https://github.com/comahe-de/i18n4k/tree/34-how-to-handle-same-language-for-different-countries
> 
> You may check it out and run "gradle publishToMavenLocal" to try it locally (by using version "0.7.0-SNAPSHOT")

I'm sorry for the very late reply. 

I tested if with 2 different locale (`en_US` and `pt_BR`) and it works like a charm. Thanks for jumping into that so quickly!

**Comment by trentkan** [comment]
Is there a specific version of xcode that required to build this locally?

**Comment by trentkan** [comment]
I think one thing missing here is to along with adding the `mavenLocal()` line to the `settings.gradle.kts`, we  also need to add it to the repositories block within `build.gradle.kts`
