### ISSUE TITLE
Add dependencies to "generate18n4KFiles"-task for task in an Andoird/Multiplatfrom project, to execute task before build

### ISSUE THREAD

**Issue by Shabinder** [comahe-de/i18n4k#4]
In Gradle KTS how to achieve as described in title, I am having hard time doing that for some reason, see below for ref on How I was proceeding

![image](https://user-images.githubusercontent.com/44765050/125409710-cce68580-e3d9-11eb-8edd-474e0aaecfdc.png)

**Comment by comahe-de** [comment]
@Shabinder try it in an afterEvaluate blok

    afterEvaluate{
        ...
    }

**Comment by comahe-de** [comment]
@Shabinder Hm, normally it should execute be for the build task. It is configured tu run before the following tasks:  compileKotlin, compileJava, compileKotlinJvm, compileKotlinJs, compileKotlinNative, compileKotlinMetadata

Don't you have this tasks in your project?

**Comment by Shabinder** [comment]
I do have , but for some reason it doesnt execute:

Let me share you live error:

BUILD LOG: https://monitor.f-droid.org/builds/log/com.shabinder.spotiflyer/22
source code: https://github.com/Shabinder/SpotiFlyer

**Comment by comahe-de** [comment]
This Android setup creates many other task but non of the mentioned above. 

With the following addition it is executed on my machine. I just used a task that was early in my log. You may choose an other task name.

    // needed as the Android setup generates other task names that the normal setups
    // Can be removed when this issue is fixed: https://github.com/comahe-de/i18n4k/issues/4
    tasks.findByName("compileCommonMainKotlinMetadata")
        ?.dependsOn(de.comahe.i18n4k.gradle.plugin.GENERATE_I18N_SOURCES_TASK_NAME)

**Comment by comahe-de** [comment]
Hi I have looked at your project and saw you good solution for the problem: 

    tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
        dependsOn(":common:data-models:generateI18n4kFiles")
        kotlinOptions { jvmTarget = "1.8" }
    }

I now have applied a similar solution in the plugin (commit: c24938ee7f827844a2b320b7e619a64a83e73501)
