### ISSUE TITLE
Select-Pattern

### ISSUE THREAD

**Issue by comahe-de** [comahe-de/i18n4k#42]
Select a text value based on the value of the parameter.

Format:

    { PARAMETER_NUMBER, select, VALUE1:  TEXT1 | VALUE2 / VALUE3:  TEXT2 | <VALUE_REGEX> : TEXT_REGEX | ? OTHERWISE_TEXT}
   

- PARAMETER_NUMBER: 
  - Number of the parameter which values is matched against the values of the select list
- VALUE*: 
  - If a values matches the value of the parameter, the corresponding text (TEXT*) is selected
  - List of several values for the same text can be separated by slash "/"
- VALUE_REGEX 
  - When the value is surrounded by "<" and ">" it is seen as regex, e.g. `<([A-Z])\w+>` 
  - If the regex matches the value of the parameter, the corresponding text (TEXT_REGEX) is selected
- TEXT*: 
  - Text that is returned by the pattern if the value matches the value of the parameter 
  - Texts themselves can also contain patterns. So, the patterns can be nested. 
- TEXT_REGEX 
  - Like TEXT* but regex-groups can be refereed by <GROUP_NUMBER> 
- OTHERWISE_TEXT
  - If non of the values before matched, this text will be selected
  - If there is no OTHERWISE_TEXT specified and no value matches, an empty string is returned

Values and texts are trimmed (leading and tailing whitespaces are removed) and must not contain "," , "/", "\", "<", ">" or "|". If these special characters are needed, they can be escaped via backslash "\".

Example:

    {0} has forgotten {1, select, female # her | ? his }  {3, select, one # bag | ? {2} bags}.

Usage:

    FORGOTTEN_BAG("Peter", "male", 1, "one") 
    -> Peter has forgotten his bag.

    FORGOTTEN_BAG("Mary", "female", 2, "few")
    -> Mary has forgotten her 2 bags.

**Comment by CodeServant** [comment]
So to be clear the **pattern** is this new construct in curly braces and **not regex pattern** as in [JAVA](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) or [Kotlin](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/-regex/).

**Comment by comahe-de** [comment]
@CodeServant, yes I mean the construct in curly braces.

**Comment by trentkan** [comment]
While I understand the request, I wonder if it makes sense to complicate the codebase with programmatically figuring out the gender of words, when we could solve the same problem with two entries in the message bundle.
