### ISSUE TITLE
Parameters surrounded by single quote are not detected by the generator

### ISSUE THREAD

**Issue by nuke-dash** [comahe-de/i18n4k#58]
In the properties file you have this string for exmaple.  
```setup.qr.login.description=To continue, please scan the QR code below with your mobile device.\nOr go to this URL '{0}'\nand enter this code '{1}'.``` 
The generate code is.  
```
/**
   * To continue, please scan the QR code below with your mobile device.
   * Or go to this URL '{0}'
   * and enter this code '{1}'.
   */
  @JvmStatic
  public val setup_qr_login_description: MessageBundleLocalizedString =
      getLocalizedString0("setup.qr.login.description", 175)
```

So it doesn't take the {0} and {1} into account.  

But if you add the {0} and {1} without single quote.

```setup.qr.login.description=To continue, please scan the QR code below with your mobile device.{0}{1}\nOr go to this URL '{0}'\nand enter this code '{1}'.``` 
It detects those two.
```
/**
   * To continue, please scan the QR code below with your mobile device.{0}{1}
   * Or go to this URL '{0}'
   * and enter this code '{1}'.
   */
  @JvmStatic
  public val setup_qr_login_description: MessageBundleLocalizedString =
      getLocalizedString2("setup.qr.login.description", 175)
```

**Comment by comahe-de** [comment]
The sign `'` is used to escape special chars. That's why "{1}" is not recognized in "...enter this code '{1}'" Write `''`  if you want to have a `'` in the output

**Comment by nuke-dash** [comment]
Thanks, I just noticated it's related to the single quote.
So double singel quote to use a single quote 👍
