### ISSUE TITLE
Double single quotes are not escaped in string without parameters

### ISSUE THREAD

**Issue by nuke-dash** [comahe-de/i18n4k#59]
Related to https://github.com/comahe-de/i18n4k/issues/58

When a string contains no variables then two single quotes are not "escaped", the resulting string still shows the two quotes.
For example: "Let''s finish setting up your device ...".
This will display "Let''s ..." instead of "Let's".
Using a string that contains parameters then two single quotes are escaped as expected.
e.g. "Go to to this URL ''{0}''\nand enter this code ''{1}''". add "Let''s" e.g. "Let's go to to this URL ''{0}''\nand enter this code ''{1}''".
This will then display "Let's go to to this URL 'https://localhost/login' .... ".

Is this working as designed?
If no, then I'm hoping this can be fixed :) 
If yes, then isn't it confusing that "sometimes" you need double single quotes and other times only one single quote?
Won't it make more sense to always use the single quote escaping logic?

**Comment by comahe-de** [comment]
Hi @nuke-dash ,

You found a bug. I will fix it soon.

**Comment by comahe-de** [comment]
Fixed in release 0.7.1. Should be available in some hours.
