### ISSUE TITLE
Apostrophe's character gets removed automatically

### ISSUE THREAD

**Issue by XibalbaM** [comahe-de/i18n4k#65]
Hi ! I'm trying to use the library for my website, but I can't get this translation to work : 
```
title={0} - {1}'s
```
When I call `CommonText.title("a", "b")`, I get `a - bs`. I tried to put a backslash before, and to replace it with \u0027, but it didn't work. 
I guess you're removing the apostrophe for some reason.

Btw here is my config if it can help
```kt
i18n4k {
    sourceCodeLocales = languages
    inputDirectory = "src/jsMain/i18n"
}
```

**Comment by comahe-de** [comment]
Hi, you need to write a double apostrophe.

See here: https://github.com/comahe-de/i18n4k/blob/master/doc/escaping.adoc
