### ISSUE TITLE
[BUG]: Accents are not exported correctly

### ISSUE THREAD

**Issue by Distractic** [comahe-de/i18n4k#69]
Hello

In my French properties file, I have a sentence with an accent like:
```properties
test=J'étais un bug
```

However, the generated class for French is:
```kt
private object Messages_fr : MessagesProvider {
  @JvmStatic
  private val _data: Array<String?> = arrayOf(
      "J'�tais un bug")

  override val locale: Locale = forLocaleTag("fr")

  override val size: Int
    get() = _data.size

  override fun `get`(index: Int): String? = _data[index]
}
```

As you can see,  the `é` becomes `�`.

Is there a problem with the encoding between properties files and Kotlin files?

**Comment by comahe-de** [comment]
Please check that the files are stored in correct encoding. See #25

**Comment by comahe-de** [comment]
Please check that the files are stored in correct encoding. See #25. 



And the apostrophe needs to be a double apostrophe. See #65.

**Comment by Distractic** [comment]
Thanks a lot! That was a encoding problem from my IDE.
