### ISSUE TITLE
No of the supported Kotlin-Plugins (multiplatform, js, native, jvm) has be applied to the project

### ISSUE THREAD

**Issue by ArnauKokoro** [comahe-de/i18n4k#9]
@comahe-de @Shabinder When re-building gradle on the project with:

```
plugins {
    id("de.comahe.i18n4k") version "0.1.3"
} 
```

it thows: 'No of the supported Kotlin-Plugins (multiplatform, js, native, jvm) has be applied to the project'

**Comment by comahe-de** [comment]
@ArnauKokoro Do you have an example project that throws this error?

This error can be avoid when setting the `generationTargetPlatform` field in the [plugin config](../tree/master/i18n4k-gradle-plugin/src/main/kotlin/de/comahe/i18n4k/gradle/plugin/I18n4kExtension.kt#generationTargetPlatform) (see also [GenerationTargetPlatform](../tree/master/i18n4k-generator/src/main/kotlin/de/comahe/i18n4k/generator/GenerationTargetPlatform.kt))

e.g.

```kotlin
i18n4k {
    generationTargetPlatform = de.comahe.i18n4k.generator.GenerationTargetPlatform.MULTI_PLATFORM 
}
```

**Comment by zeromod** [comment]
@comahe-de Is it possible to add `org.jetbrains.kotlin.android` to the plugin checks in `I18n4kPlugin` ? So that I can apply this plugin in an android project ?

**Comment by comahe-de** [comment]
@zeromod I have added Android support for the generation plugin in version 0.5.0. Will be available within the next day. May you can have a try...
